//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Dal.Dapper.SqlScripts.ProductRepository {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Dal.Dapper.SqlScripts.ProductRepository.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @CategoryID int = (SElECT [CategoryID] FROM [dbo].[Categories] WHERE [CategoryName] = @CategoryName);
        ///IF @CategoryID IS NULL
        ///BEGIN
        ///    INSERT INTO [dbo].[Categories] ([CategoryName], [Description])
        ///    VALUES (@CategoryName, @CategoryDescription);
        ///
        ///    SET @CategoryID = SCOPE_IDENTITY();
        ///END;
        ///
        ///DECLARE @SupplierID int = (SElECT [SupplierID] FROM [dbo].[Suppliers] WHERE [CompanyName] = @SupplierName);
        ///IF @SupplierID IS NULL
        ///BEGIN
        ///    INSERT INTO [dbo].[Suppliers] ([CompanyName], [ContactNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [p].[ProductID]
        ///      ,[p].[ProductName]
        ///      ,[p].[QuantityPerUnit]
        ///      ,[p].[UnitPrice]
        ///      ,[p].[UnitsInStock]
        ///      ,[p].[UnitsOnOrder]
        ///      ,[p].[ReorderLevel]
        ///      ,[p].[Discontinued]
        ///      ,[c].[CategoryID]
        ///      ,[c].[CategoryName]
        ///      ,[c].[Description]
        ///      ,[s].[SupplierID]
        ///      ,[s].[CompanyName]
        ///      ,[s].[ContactName]
        ///  FROM [dbo].[Products] AS [p]
        ///  LEFT JOIN [dbo].[Categories] AS [c]
        ///    ON [p].[CategoryID] = [c].[CategoryID]
        ///  LEFT JOIN [dbo].[Suppliers]  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [dbo].[Products]
        ///SET [CategoryID] = @CategoryID
        ///WHERE [ProductID] = @ProductID;
        ///.
        /// </summary>
        internal static string ReplaceToCategory {
            get {
                return ResourceManager.GetString("ReplaceToCategory", resourceCulture);
            }
        }
    }
}
