//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Dal.Dapper.SqlScripts.EmployeeRepository {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Dal.Dapper.SqlScripts.EmployeeRepository.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT [dbo].[Employees] ([EmployeeID], [LastName], [FirstName])
        ///VALUES (@EmployeeID, @LastName, @FirstName)
        ///
        ///SELECT [EmployeeID]
        ///      ,[LastName]
        ///      ,[FirstName]
        ///FROM [dbo].[Employees]
        ///WHERE [EmployeeID] IN (SELECT SCOPE_IDENTITY());
        ///.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT [dbo].[EmployeeTerritories] ([EmployeeID], [TerritoryID])
        ///VALUES (@EmployeeID, @TerritoryID)
        ///.
        /// </summary>
        internal static string AddEmployeeTerritory {
            get {
                return ResourceManager.GetString("AddEmployeeTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Employees TABLE
        ///(
        ///    [EmployeeID] int,
        ///    [LastName] nvarchar(20),
        ///    [FirstName] nvarchar(10)
        ///);
        ///
        ///INSERT INTO @Employees
        ///SELECT [EmployeeID]
        ///      ,[LastName]
        ///      ,[FirstName]
        ///FROM [dbo].[Employees];
        ///
        ///DECLARE @EmployeesRegions TABLE
        ///(
        ///    [EmployeeID] int,
        ///    [RegionID] int
        ///);
        ///
        ///INSERT INTO @EmployeesRegions
        ///SELECT [ET].[EmployeeID]
        ///      ,[T].[RegionID]
        ///FROM [dbo].[EmployeeTerritories] AS [ET]
        ///JOIN [dbo].[Territories] AS [T]
        ///  ON [ET].[TerritoryID] = [T].[TerritoryID] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetWithRegions {
            get {
                return ResourceManager.GetString("GetWithRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Employees TABLE
        ///(
        ///    [EmployeeID] int,
        ///    [LastName] nvarchar(20),
        ///    [FirstName] nvarchar(10)
        ///);
        ///
        ///INSERT INTO @Employees
        ///SELECT [EmployeeID]
        ///      ,[LastName]
        ///      ,[FirstName]
        ///FROM [dbo].[Employees];
        ///
        ///DECLARE @EmployeesShippers TABLE
        ///(
        ///    [EmployeeID] int,
        ///    [ShipperID] int
        ///);
        ///
        ///INSERT INTO @EmployeesShippers
        ///SELECT [E].[EmployeeID]
        ///      ,[O].[ShipVia]
        ///FROM [dbo].[Employees] AS [E]
        ///LEFT JOIN [dbo].[Orders] AS [O]
        ///  ON [E].[EmployeeID] = [O].[EmployeeID]
        ///GROUP BY [E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetWithShippers {
            get {
                return ResourceManager.GetString("GetWithShippers", resourceCulture);
            }
        }
    }
}
